### PR TITLE
Fix iOS bridge header importing style

### PR DESCRIPTION
**Pull request by orab**
In Xcode 10.3, it will report an error: "'native_state/native_state-Swift.h' file not found".

### CODE REVIEW

**Comment by hvisser** [comment]
Thanks, does this also work on older xcode versions? I remember mucking around with this before :)

**Comment by orab** [comment]
I don't test on other versions, but if we reference header file from the same module, we should always use  "" instead of <>.

> Thanks, does this also work on older xcode versions? I remember mucking around with this before :)

**Comment by hvisser** [comment]
I tried your change using Xcode 11.2 but that yields a compilation issue, while the current develop branch works. So I don't think this change can be merged as is:

```Xcode build done.                                            5.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/hugo/tmp/flutter-native-state/ios/Classes/FlutterNativeStatePlugin.m:2:9: fatal error: 'native_state-Swift.h' file not
    found
    #import "native_state-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

It might work on 10.3, I haven't tried, but I assume most Flutter users will use an up to date Xcode version too.

**Comment by orab** [comment]
Sorry, the problem seems to caused by Pod configs. 

In our project, we don't use the `use_frameworks!` instruction, so the plugin will be compiled as static library. There is a related [issue](https://github.com/flutter/flutter/issues/40133) in flutter project.

Maybe I should fix it only in forked version, I'll close this PR.
